import '@/styles/index.scss';

import clsx from 'clsx';
import {ReactNode} from 'react';

import MainNav from '@/components/mainNav/mainNav.tsx';

import {latoFont} from './fonts.ts';
import styles from './layout.module.scss';

export const metadata = {
  title: 'SW BaseExp NextJs',
  description: 'Generated by create-nx-workspace',
};

type RootLayoutProps = {
  children: ReactNode;
};

const RootLayout = ({children}: RootLayoutProps) => {
  // TODO
  // const navigation = useNavigation();

  return (
    <html lang="en" className={latoFont.className} data-theme="light">
      <body>
        <div className={styles.appLayout}>
          <header className={clsx(styles.appHeader)}>
            {/*<header className={clsx(styles.appHeader, navigation.state === 'loading' && styles.appLoading)}>*/}
            <h1>SW NextExp</h1>
            <MainNav />
          </header>
          <main className={styles.appMain}>{children}</main>
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
